# Generated by Django 3.0.6 on 2020-08-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_remove_register_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='message',
        ),
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='adhar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='designation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
