# Generated by Django 3.0.6 on 2020-08-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_auto_20200821_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='adhar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
