# Generated by Django 3.0.6 on 2020-08-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='examdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
