# Generated by Django 3.0.6 on 2020-09-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200901_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
